# Generated by Django 4.1.5 on 2023-02-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_create_new_objects'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boardparticipant',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='boardparticipant',
            name='board',
        ),
        migrations.RemoveField(
            model_name='boardparticipant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='goalcategory',
            name='board',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='BoardParticipant',
        ),
    ]
