# Generated by Django 4.1.5 on 2023-02-09 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TgUser',
        ),
    ]
